services:
  mysql:
    image: mysql:8.4
    container_name: world-mysql
    environment:
      MYSQL_DATABASE: \
      MYSQL_USER: \
      MYSQL_PASSWORD: \
      MYSQL_ROOT_PASSWORD: \
    ports:
      - "\:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p\"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: \
      DB_USER: \
      DB_PASS: \
      APP_PORT: \
    ports:
      - "\:8080"
