name: CI
on:
  push:
    branches: [ master, develop, 'feature/**', 'release/**', 'hotfix/**' ]
  pull_request:
    branches: [ master, develop ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK (Temurin 24)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
          cache: maven
      - name: Build & test
        run: mvn -B -DskipITs test
