name: CI

on:
  push:
    branches: [ master, develop, "feature/**", "release/**", "hotfix/**" ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK (Temurin 21)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Build & test
        run: mvn -B -DskipITs test

  check-dockerfile:
    runs-on: ubuntu-latest
    outputs:
      present: ${{ steps.detect.outputs.present }}
    steps:
      - uses: actions/checkout@v4
      - id: detect
        run: |
          if test -f Dockerfile; then
            echo "present=true" >> $GITHUB_OUTPUT
          else
            echo "present=false" >> $GITHUB_OUTPUT
          fi

  docker-build:
    needs: [build-test, check-dockerfile]
    if: needs.check-dockerfile.outputs.present == 'true' && github.ref_name != 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: world-pop-report:ci-${{ github.sha }}