name: CI
on:
  push:
    branches: [ master, develop, "feature/**", "release/**", "hotfix/**" ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK (Temurin 24)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "24"
          cache: maven

      - name: Build & test
        run: mvn -B -DskipITs test

  docker-build:
    name: Docker build (no push)
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4

      - id: has_dockerfile
        name: Check for Dockerfile
        shell: bash
        run: |
          if [ -f Dockerfile ]; then
            echo "present=true" >> "$GITHUB_OUTPUT"
          else
            echo "present=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Docker Buildx
        if: steps.has_dockerfile.outputs.present == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build image
        if: steps.has_dockerfile.outputs.present == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: world-pop-report:ci-${{ github.sha }}
